"""Pianoteq preset ↔ MIDI program mapping — auto-generated from pianoteq --list-presets.

All 797 presets are covered, grouped by General MIDI program number.

Usage:
    from audio_understanding.random_rendering.pianoteq_presets import get_preset, get_random_preset
    preset = get_preset(program=0)            # random piano preset
    preset = get_random_preset(rng)           # random from any instrument
    preset = get_preset(program=0, rng=rng)   # random piano preset with given rng
"""
from __future__ import annotations

from typing import Dict, List, Optional

import numpy as np

# MIDI program → list of Pianoteq presets (all 797 presets from pianoteq --list-presets)
PROGRAM_TO_PRESETS: Dict[int, List[str]] = {
    # Historical Piano (-1) — fortepianos, square pianos, virginals
    -1: [
        "Ph. Schmidt Square Original",
        "Ph. Schmidt Square Recording",
        "Ph. Schmidt Square Felt",
        "Ph. Schmidt Square Equal temp",
        "Ph. Schmidt Square Binaural",
        "Ph. Schmidt Square Werckmeister III",
        "Ph. Schmidt Square Neidhardt III",
        "Ph. Schmidt Square Mesotonic",
        "Ph. Schmidt Square Well temp",
        "J. Weimes Pianoforte Original",
        "J. Weimes Pianoforte Recording",
        "J. Weimes Pianoforte Felt",
        "J. Weimes Pianoforte Equal temp",
        "J. Weimes Pianoforte Binaural",
        "J. Weimes Pianoforte Werckmeister III",
        "J. Weimes Pianoforte Neidhardt III",
        "J. Weimes Pianoforte Mesotonic",
        "J. Weimes Pianoforte Well temp",
        "NY Steinway Square Original",
        "NY Steinway Square Recording",
        "NY Steinway Square Felt",
        "NY Steinway Square Equal temp",
        "NY Steinway Square Binaural",
        "NY Steinway Square Werckmeister III",
        "NY Steinway Square Neidhardt III",
        "NY Steinway Square Mesotonic",
        "NY Steinway Square Well temp",
        "J. Dohnal",
        "J. Dohnal Close Mic",
        "J. Dohnal 440",
        "J. Dohnal Binaural",
        "J. Dohnal Recording",
        "J. Dohnal Felt",
        "J. Dohnal Werckmeister III",
        "J. Dohnal Neidhardt III",
        "J. Dohnal mesotonic",
        "J. Dohnal well tempered",
        "I. Besendorfer",
        "I. Besendorfer Close Mic",
        "I. Besendorfer 440",
        "I. Besendorfer Binaural",
        "I. Besendorfer Recording",
        "I. Besendorfer Felt",
        "I. Besendorfer Werckmeister III",
        "I. Besendorfer Neidhardt III",
        "I. Besendorfer mesotonic",
        "I. Besendorfer well tempered",
        "S. Erard",
        "S. Erard Close Mic",
        "S. Erard 440",
        "S. Erard Binaural",
        "S. Erard Recording",
        "S. Erard Felt",
        "S. Erard Werckmeister III",
        "S. Erard Neidhardt III",
        "S. Erard mesotonic",
        "S. Erard well tempered",
        "J.B. Streicher",
        "J.B. Streicher Close Mic",
        "J.B. Streicher 440",
        "J.B. Streicher Binaural",
        "J.B. Streicher Recording",
        "J.B. Streicher Felt",
        "J.B. Streicher Werckmeister III",
        "J.B. Streicher Neidhardt III",
        "J.B. Streicher mesotonic",
        "J.B. Streicher well tempered",
        "J. Broadwood",
        "J. Broadwood Close Mic",
        "J. Broadwood 440",
        "J. Broadwood Binaural",
        "J. Broadwood Recording",
        "J. Broadwood Felt",
        "J. Broadwood Werckmeister III",
        "J. Broadwood Neidhardt III",
        "J. Broadwood mesotonic",
        "J. Broadwood well tempered",
        "I. Pleyel",
        "I. Pleyel Close Mic",
        "I. Pleyel 440",
        "I. Pleyel Binaural",
        "I. Pleyel Revoiced",
        "I. Pleyel Recording",
        "I. Pleyel Felt",
        "I. Pleyel Werckmeister III",
        "I. Pleyel Neidhardt III",
        "I. Pleyel mesotonic",
        "I. Pleyel well tempered",
        "J. Frenzel",
        "J. Frenzel Close Mic",
        "J. Frenzel 440",
        "J. Frenzel Binaural",
        "J. Frenzel Recording",
        "J. Frenzel Felt",
        "J. Frenzel Werckmeister III",
        "J. Frenzel Neidhardt III",
        "J. Frenzel mesotonic",
        "J. Frenzel well tempered",
        "C. Bechstein",
        "C. Bechstein Close Mic",
        "C. Bechstein Under Lid",
        "C. Bechstein 440",
        "C. Bechstein Binaural",
        "C. Bechstein Recording",
        "C. Bechstein Felt",
        "C. Bechstein Werckmeister III",
        "C. Bechstein Neidhardt III",
        "C. Bechstein mesotonic",
        "C. Bechstein well tempered",
    ],
    # Acoustic Grand Piano (0) — all modern grands + upright U4
    0: [
        "NY Steinway D Classical",
        "NY Steinway D Jazz",
        "NY Steinway Model D",
        "NY Steinway D Binaural",
        "NY Steinway D Sombre",
        "NY Steinway D Classical Recording",
        "NY Steinway D Jazz Recording",
        "NY Steinway D Chamber Recording",
        "NY Steinway D Mix",
        "NY Steinway D Mono",
        "NY Steinway D New Age",
        "NY Steinway D Player",
        "NY Steinway D Under Lid",
        "NY Steinway D Prelude",
        "NY Steinway D Felt I",
        "NY Steinway D Felt II",
        "NY Steinway D Bass & Piano split",
        "NY Steinway D Gentle",
        "NY Steinway D Warm",
        "NY Steinway D Cinematic",
        "NY Steinway D Prepared",
        "NY Steinway D Honky Tonk",
        "NY Steinway D Worn Out",
        "NY Steinway D Ruined",
        "NY Steinway D Hybrid",
        "NY Steinway D Bowed",
        "HB Steinway D Classical",
        "HB Steinway D Jazz",
        "HB Steinway D Mix",
        "HB Steinway D Sombre",
        "HB Steinway D New Age",
        "HB Steinway D Prelude",
        "HB Steinway D Felt I",
        "HB Steinway D Felt II",
        "HB Steinway Model D",
        "HB Steinway D Binaural",
        "HB Steinway D Classical Recording",
        "HB Steinway D Jazz Recording",
        "HB Steinway D Mono",
        "HB Steinway D Bass & Piano split",
        "HB Steinway D Intimate",
        "HB Steinway D Warm",
        "HB Steinway D Cinematic",
        "HB Steinway D Player",
        "HB Steinway D Under Lid",
        "HB Steinway D Bright",
        "HB Steinway D Prepared",
        "HB Steinway D Honky Tonk",
        "HB Steinway D Worn Out",
        "HB Steinway D Hybrid",
        "Steinway B Warm",
        "Steinway B Improv",
        "Steinway B Prelude",
        "Steinway Model B",
        "Steinway B Binaural",
        "Steinway B Bright",
        "Steinway B Sombre",
        "Steinway B Gentle",
        "Steinway B Felt I",
        "Steinway B Felt II",
        "Steinway B Wide",
        "Steinway B Recording 1",
        "Steinway B Recording 2",
        "Steinway B Recording 3",
        "Steinway B Mono",
        "Steinway B Intimate",
        "Steinway B Player",
        "Steinway B Under Lid",
        "Steinway B Close Mic",
        "Steinway B Distant Mic",
        "Steinway B Late Evening",
        "Steinway B Cinematic",
        "Steinway B Dreamy",
        "Steinway B Cosmic",
        "Shigeru Kawai SK-EX Warm",
        "Shigeru Kawai SK-EX Ryuyo",
        "Shigeru Kawai SK-EX Binaural",
        "Shigeru Kawai SK-EX Classical Recording",
        "Shigeru Kawai SK-EX Sombre",
        "Shigeru Kawai SK-EX Jazz Recording",
        "Shigeru Kawai SK-EX Chamber Recording",
        "Shigeru Kawai SK-EX Mix",
        "Shigeru Kawai SK-EX Mono",
        "Shigeru Kawai SK-EX New Age",
        "Shigeru Kawai SK-EX Player",
        "Shigeru Kawai SK-EX Prelude",
        "Shigeru Kawai SK-EX Felt I",
        "Shigeru Kawai SK-EX Felt II",
        "Shigeru Kawai SK-EX Bass & Piano split",
        "Shigeru Kawai SK-EX Heroic",
        "Shigeru Kawai SK-EX Cosmic",
        "Shigeru Kawai SK-EX with Strings Pad",
        "Bösendorfer VC Warm",
        "Bösendorfer VC Classical Recording",
        "Bösendorfer VC Jazz Recording",
        "Bösendorfer VC Sombre",
        "Bösendorfer VC Pop Mix",
        "Bösendorfer VC Mono",
        "Bösendorfer VC New Age",
        "Bösendorfer VC Player",
        "Bösendorfer 280VC",
        "Bösendorfer VC Binaural",
        "Bösendorfer VC Felt I",
        "Bösendorfer VC Felt II",
        "Bösendorfer VC Cinematic",
        "Bösendorfer VC Bass & Piano split",
        "Bösendorfer VC Dreamy",
        "Bösendorfer VC Bright",
        "C. Bechstein DG Warm",
        "C. Bechstein DG Prelude",
        "C. Bechstein DG Sweet",
        "C. Bechstein DG Sombre",
        "C. Bechstein DG Felt I",
        "C. Bechstein DG Felt II",
        "C. Bechstein DG D 282",
        "C. Bechstein DG Binaural",
        "C. Bechstein DG Recording 1",
        "C. Bechstein DG Recording 2",
        "C. Bechstein DG Recording 3",
        "C. Bechstein DG Mono",
        "C. Bechstein DG Cinematic",
        "C. Bechstein DG Snappy",
        "C. Bechstein DG Bass & Piano split",
        "C. Bechstein DG Venue",
        "C. Bechstein DG Player",
        "C. Bechstein DG Under Lid",
        "C. Bechstein DG Cosmic",
        "C. Bechstein DG Broken",
        "Ant. Petrof Warm",
        "Ant. Petrof Prelude",
        "Ant. Petrof Sombre",
        "Ant. Petrof Felt I",
        "Ant. Petrof Felt II",
        "Ant. Petrof Venue",
        "Ant. Petrof 275",
        "Ant. Petrof Binaural",
        "Ant. Petrof Recording 1",
        "Ant. Petrof Recording 2",
        "Ant. Petrof Recording 3",
        "Ant. Petrof Mono",
        "Ant. Petrof Cinematic",
        "Ant. Petrof Bass & Piano split",
        "Ant. Petrof Intimate",
        "Ant. Petrof Player",
        "Ant. Petrof Under Lid",
        "Ant. Petrof Duo",
        "Ant. Petrof Dreamy",
        "Ant. Petrof Cosmic",
        "Ant. Petrof Broken",
        "Petrof Mistral Warm",
        "Petrof Mistral Prelude",
        "Petrof Mistral Sombre",
        "Petrof Mistral Felt I",
        "Petrof Mistral Felt II",
        "Petrof Mistral Venue",
        "Petrof 284 Mistral",
        "Petrof Mistral Binaural",
        "Petrof Mistral Classical Recording",
        "Petrof Mistral Jazz Recording",
        "Petrof Mistral Mono",
        "Petrof Mistral Cinematic",
        "Petrof Mistral Bass & Piano split",
        "Petrof Mistral Intimate",
        "Petrof Mistral Player",
        "Petrof Mistral Under Lid",
        "Petrof Mistral Gentle",
        "Petrof Mistral Dreamy",
        "Petrof Mistral Cosmic",
        "Petrof Mistral Broken",
        "Steingraeber Warm",
        "Steingraeber Prelude",
        "Steingraeber Bright",
        "Steingraeber Sombre",
        "Steingraeber Felt I",
        "Steingraeber Felt II",
        "Steingraeber E-272",
        "Steingraeber Binaural",
        "Steingraeber Recording 1",
        "Steingraeber Recording 2",
        "Steingraeber Recording 3",
        "Steingraeber Mono",
        "Steingraeber Cinematic",
        "Steingraeber Bass & Piano split",
        "Steingraeber Player",
        "Steingraeber Intimate",
        "Steingraeber Under Lid",
        "Steingraeber Dreamy",
        "Steingraeber Cosmic",
        "Steingraeber Prepared",
        "Steingraeber Broken",
        "Grotrian Warm",
        "Grotrian Prelude",
        "Grotrian Sombre",
        "Grotrian Felt I",
        "Grotrian Felt II",
        "Grotrian Concert Royal",
        "Grotrian Binaural",
        "Grotrian Recording 1",
        "Grotrian Recording 2",
        "Grotrian Recording 3",
        "Grotrian Mono",
        "Grotrian Intimate",
        "Grotrian Cabaret",
        "Grotrian Player",
        "Grotrian Player Wide",
        "Grotrian Under Lid",
        "Blüthner Improv",
        "Blüthner Model One",
        "Blüthner Binaural",
        "Blüthner Prelude",
        "Blüthner Sombre",
        "Blüthner Warm",
        "Blüthner Felt I",
        "Blüthner Felt II",
        "Blüthner Studio Recording",
        "Blüthner Chamber Recording",
        "Blüthner Concert Recording",
        "Blüthner Mono",
        "Blüthner Cinematic",
        "Blüthner Player",
        "Blüthner Intimate",
        "YC5 Focus",
        "YC5 Improv",
        "YC5 Bright",
        "YC5 Sombre",
        "YC5 Warm",
        "YC5 Felt I",
        "YC5 Felt II",
        "YC5 Basic",
        "YC5 Binaural",
        "YC5 Solo Recording",
        "YC5 Jazz Recording",
        "YC5 Mix Recording",
        "YC5 Mono",
        "YC5 Close Mic",
        "YC5 Vintage",
        "YC5 Pop",
        "YC5 Player",
        "YC5 Worn Out",
        "K2 Warm",
        "K2 Focus",
        "K2 Basic",
        "K2 Binaural",
        "K2 Sombre",
        "K2 Felt I",
        "K2 Felt II",
        "K2 Studio Recording",
        "K2 Concert Recording",
        "K2 Mix Recording",
        "K2 Mono",
        "K2 Prelude",
        "K2 Dreamy",
        "K2 Player Jazz",
        "K2 Player Clean",
        "K2 Close Mic fig8",
        "K2 Under Lid",
        "K2 Bass & Piano split",
        "K2 Mono Compatible",
        "K2 Duophonic",
        "U4 Tall",
        "U4 Felt I",
        "U4 Felt II",
        "U4 Binaural",
        "U4 Recording",
        "U4 Tall Concert",
        "U4 a la Monk",
        "U4 Player Open",
        "U4 Player Closed",
        "U4 Player Dry",
        "U4 Back",
        "U4 Small",
        "U4 Midnight",
        "U4 Americana",
        "U4 Jazz",
        "U4 Pop",
        "U4 Vintage",
        "U4 Living Room",
        "U4 Club",
        "U4 in Hall",
        "U4 Bierkeller",
        "U4 Weathered",
        "U4 Tacky",
        "U4 Honky Tonk",
        "U4 Ruined",
        "U4 Bowed",
    ],
    # Electric Piano 1 (4) — Rhodes MKI, Pianet N/T
    4: [
        "MKI Tremo",
        "MKI Basic",
        "MKI Basic Mono",
        "MKI Binaural",
        "MKI Bark",
        "MKI Soft",
        "MKI Bright",
        "MKI Low Dyn",
        "MKI Wet EP",
        "MKI Cinematic",
        "MKI Gentle Chorus 1",
        "MKI Gentle Chorus 2",
        "MKI Soft Chorus",
        "MKI Punchy Chorus",
        "MKI Groovy Chorus",
        "MKI Sweet Flanger",
        "MKI Leslie",
        "MKI Comp 1",
        "MKI Comp 2",
        "MKI Gritty 1",
        "MKI Gritty 2",
        "MKI Amped",
        "MKI Overdriven",
        "MKI Octave",
        "MKI Roomy",
        "MKI Bamboo",
        "MKI Rain Stick",
        "MKI Thick Pad",
        "MKI Warm Lead 1",
        "MKI Warm Lead 2",
        "MKI Wailing Overdrive",
        "MKI Blooming Grit",
        "Pianet N Basic",
        "Pianet N 80s Band",
        "Pianet N Jazz Trio",
        "Pianet N Comp",
        "Pianet N Roomy",
        "Pianet N Binaural",
        "Pianet N Funky",
        "Pianet N Little Fuzzy",
        "Pianet N Metalizer",
        "Pianet N Orion Echo",
        "Pianet N Psychedelics",
        "Pianet N Studio",
        "Pianet N The 60s Beat",
        "Pianet N Wired",
        "Pianet N Mono",
        "Pianet T Basic",
        "Pianet T Mono",
        "Pianet T Bamboo",
        "Pianet T Bright",
        "Pianet T Concrete",
        "Pianet T Cosmic",
        "Pianet T Jazzy",
        "Pianet T Regular",
        "Pianet T Roomy",
        "Pianet T Binaural",
        "Pianet T Roomy 2",
        "Pianet T Soft Pan Tremolo",
        "Pianet T Wooden",
    ],
    # Electric Piano 2 (5) — Rhodes MKII, Wurlitzer W1/W2
    5: [
        "MKII Spark",
        "MKII Room Close Mic",
        "MKII Room Distant Mic",
        "MKII Jazzy",
        "MKII Soft",
        "MKII Bark",
        "MKII Super Bark",
        "MKII Basic Stereo",
        "MKII Basic Mono",
        "MKII Binaural",
        "MKII 60s Beat",
        "MKII 70s Fusion",
        "MKII Dogs EP",
        "MKII DynaComp EP",
        "MKII EAP Piano",
        "MKII FM alike",
        "MKII Flower Power",
        "MKII Jazzrocker",
        "MKII New Age Dreams",
        "MKII Paddy",
        "MKII Pinhead EP",
        "MKII RMI Clone",
        "MKII Rocks",
        "MKII Smooth",
        "MKII Songwriter",
        "MKII Split Manual",
        "MKII Stage EP",
        "MKII Sweet n Dyna",
        "MKII Tremolo EP",
        "MKII Vibrant",
        "MKII Wurhds",
        "MKII Broken",
        "MKII Bowed",
        "W2 Basic Mono",
        "W2 Basic Stereo",
        "W2 Binaural",
        "W2 Bright",
        "W2 Soft",
        "W2 Roomy",
        "W2 Logical",
        "W2 You're my best friend",
        "W2 Where it's at",
        "W2 Warm",
        "W2 Flange",
        "W2 Wah",
        "W2 Tremo",
        "W2 Comp",
        "W2 Overdriven",
        "W2 Octave",
        "W2 60s Pop Soft",
        "W2 AmericanPop Soft",
        "W2 AmericanRock Backing",
        "W2 AmericanRock Trem",
        "W2 BritPop Power",
        "W2 BritRock Decay Trem",
        "W2 BritRock Dyna",
        "W2 BritRock Power",
        "W2 BritRock Room",
        "W2 BritRock Stage Twin",
        "W2 ClassicRock 60s Crunch",
        "W2 JazzRock General",
        "W2 JazzRock Mechanical",
        "W2 JazzRock Warm",
        "W2 Pop EP",
        "W2 ReedTines",
        "W2 Rock wet",
        "W2 RockPop Wet",
        "W2 Roomy Knocker",
        "W2 Songwriter",
        "W2 Bowed",
        "W1 Basic Mono",
        "W1 Basic Stereo",
        "W1 Binaural",
        "W1 Bright",
        "W1 Soft",
        "W1 Roomy",
        "W1 Logical",
        "W1 You're my best friend",
        "W1 Where it's at",
        "W1 Warm",
        "W1 Flange",
        "W1 Wah",
        "W1 Tremo",
        "W1 Comp",
        "W1 Overdriven",
        "W1 Octave",
    ],
    # Harpsichord (6)
    6: [
        "H. Ruckers II Harpsichord L8'",
        "H. Ruckers II Harpsichord U8'",
        "H. Ruckers II Harpsichord 4'",
        "H. Ruckers II Harpsichord L8' + U8'",
        "H. Ruckers II Harpsichord L8' + 4'",
        "H. Ruckers II Harpsichord U8' + 4'",
        "H. Ruckers II Harpsichord L8' + U8' + 4'",
        "H. Ruckers II Harpsichord Player",
        "H. Ruckers II Harpsichord Binaural",
        "H. Ruckers II Harpsichord Recording",
        "H. Ruckers II Harpsichord Dynamic",
        "H. Ruckers II Harpsichord L8' Bowed",
        "J. Salodiensis Virginal Original",
        "J. Salodiensis Virginal Recording",
        "J. Salodiensis Virginal Equal temp",
        "J. Salodiensis Virginal Binaural",
        "J. Salodiensis Virginal Werckmeister III",
        "J. Salodiensis Virginal Neidhardt III",
        "J. Salodiensis Virginal Mesotonic",
        "J. Salodiensis Virginal Well temp",
        "G. Giusti Harpsichord Original",
        "G. Giusti Harpsichord Recording",
        "G. Giusti Harpsichord Equal temp",
        "G. Giusti Harpsichord Binaural",
        "G. Giusti Harpsichord Werckmeister III",
        "G. Giusti Harpsichord Neidhardt III",
        "G. Giusti Harpsichord Mesotonic",
        "G. Giusti Harpsichord Well temp",
    ],
    # Clavinet (7)
    7: [
        "Clavinet D6 Basic",
        "Clavinet D6 Stage",
        "Clavinet D6 Mono",
        "Clavinet D6 Dirty",
        "Clavinet D6 Auto-Wah",
        "Clavinet D6 Envelope-Wah",
        "Clavinet D6 Warm Amp",
        "Clavinet D6 Comp",
        "Clavinet D6 Overdriven",
        "Clavinet D6 Growl",
        "Clavinet D6 Roomy",
        "Clavinet D6 Binaural",
        "Clavinet D6 BD",
    ],
    # Celesta (8)
    8: [
        "Celesta Tremo",
        "Celesta Binaural",
        "Celesta Original",
        "Celesta Bright",
        "Celesta Sustain",
        "Celesta Mute 1",
        "Celesta Mute 2",
    ],
    # Glockenspiel (9)
    9: [
        "Glockenspiel Humanized",
        "Glockenspiel Binaural",
        "Glockenspiel Soft",
        "Glockenspiel Original",
        "Glockenspiel Sustain",
        "Glockenspiel Mute 1",
        "Glockenspiel Mute 2",
        "Glockenspiel a la piano",
    ],
    # Music Box / Toy Piano (10)
    10: [
        "Toy Piano for Amelie",
        "Toy Piano Binaural",
        "Toy Piano Original",
        "Toy Piano Dry",
        "Toy Piano a la piano",
        "Toy Piano Muted",
    ],
    # Vibraphone (11)
    11: [
        "Vibraphone V-B Tremo",
        "Vibraphone V-B Binaural",
        "Vibraphone V-B Humanized",
        "Vibraphone V-B Original",
        "Vibraphone V-B Soft",
        "Vibraphone V-B Bright",
        "Vibraphone V-B Mute 1",
        "Vibraphone V-B Mute 2",
        "Vibraphone V-B Bowed",
        "Vibraphone V-M Tremo",
        "Vibraphone V-M Binaural",
        "Vibraphone V-M Humanized",
        "Vibraphone V-M Original",
        "Vibraphone V-M Soft",
        "Vibraphone V-M Bright",
        "Vibraphone V-M Mute 1",
        "Vibraphone V-M Mute 2",
        "Vibraphone V-M Bowed",
    ],
    # Marimba (12)
    12: [
        "Marimba Humanized",
        "Marimba Binaural",
        "Marimba Original",
        "Marimba Soft",
        "Marimba Bright",
        "Marimba Edge",
        "Marimba Muted",
        "Marimba a la piano",
    ],
    # Xylophone (13)
    13: [
        "Xylophone Humanized",
        "Xylophone Binaural",
        "Xylophone Original",
        "Xylophone Soft",
        "Xylophone Bright",
        "Xylophone Edge",
        "Xylophone a la piano",
        "Xylophone Bowed",
    ],
    # Drawbar Organ (16) — MKI Organish
    16: [
        "MKI Organish 1",
        "MKI Organish 2",
    ],
    # Acoustic Guitar Nylon (24)
    24: [
        "Classical Guitar Warm",
        "Classical Guitar Arpeggio",
        "Classical Guitar a la piano",
        "Classical Guitar Prelude",
        "Classical Guitar",
        "Classical Guitar Binaural",
        "Classical Guitar Gentle",
        "Classical Guitar Triple",
        "Classical Guitar Bouzoukish Dream",
        "Classical Guitar Purists",
        "Classical Guitar Cosmic Bow",
        "Classical Guitar Stacatissimo",
        "Classical Guitar Melodic Vibrato",
        "Classical Guitar Tapping",
        "Classical Guitar Microtuned",
    ],
    # Acoustic Guitar Steel (25)
    25: [
        "Classical Guitar 12 Strings",
        "Classical Guitar Electrified",
    ],
    # Electric Guitar Clean (27) — Electra, Classical Guitar Electric
    27: [
        "Classical Guitar Electric Jazz",
        "Electra Basic",
        "Electra Mono",
        "Electra Calma Pacifica",
        "Electra Danseuse",
        "Electra Dyna 1",
        "Electra Dyna 2",
        "Electra Fatty",
        "Electra Roomy",
        "Electra Binaural",
        "Electra RubberChorus",
        "Electra Soft Rock",
        "Electra Spacy",
        "Electra Stacc",
        "Electra Strong",
    ],
    # Electric Guitar Overdriven (29)
    29: [
        "Classical Guitar Dirty",
        "Electra Overdrive Lead",
        "Electra Overdrive Lead 2",
    ],
    # Electric Bass (33) — Syngular Bass, MKII Bass
    33: [
        "MKII Piano Bass Gritty",
        "MKII Piano Bass Snappy",
        "MKII Bass & Piano split",
        "MKII Dirty Bass",
        "Syngular Bass City",
        "Syngular Bass Clockwork Heartbeat",
        "Syngular Bass Critical Mass",
        "Syngular Bass Supercritical Mass",
        "Syngular Bass Geodesic Pulse",
        "Syngular Bass Gravity Well",
        "Syngular Bass Quack",
        "Syngular Bass Saw",
        "Syngular Bass Saw Flat",
        "Syngular Bass Saw Funky",
        "Syngular Bass Slapping Saw",
        "Syngular Bass Static Displacement",
        "Syngular Bass Wide Unison",
    ],
    # Orchestral Harp (46)
    46: [
        "Concert Harp Daily",
        "Concert Harp Binaural",
        "Concert Harp Recording",
        "Concert Harp Lyrical",
        "Concert Harp Diatonic",
        "Concert Harp Player",
        "Concert Harp Brighter",
        "Concert Harp a la piano",
        "Concert Harp Dreamy",
        "Concert Harp Bowed",
        "Celtic Harp Daily",
        "Celtic Harp Binaural",
        "Celtic Harp Delicate",
        "Celtic Harp Recording",
        "Celtic Harp Sweet",
        "Celtic Harp Bright",
        "Celtic Harp Diatonic",
        "Celtic Harp Player",
        "Celtic Harp a la piano",
        "Celtic Harp Dreamy",
        "Triple Harp",
        "Triple Harp Daily",
        "Triple Harp Binaural",
        "Triple Harp Recording",
        "Triple Harp a la piano",
        "Triple Harp Spacious",
        "Triple Harp Chorused",
        "Triple Harp Steel",
    ],
    # Brass Section (61) — Syngular Brass
    61: [
        "Syngular Brass 1",
        "Syngular Brass 2",
        "Syngular Brass Section 1",
        "Syngular Brass Section 2",
    ],
    # Synth Lead (80) — Syngular Lead/Keys/Seq
    80: [
        "Syngular Init",
        "Syngular Core Sine",
        "Syngular Core Saw",
        "Syngular Core Square",
        "Syngular Core Triangle",
        "Syngular Lead Deserted Caravan",
        "Syngular Lead Electric Fairy",
        "Syngular Lead Factory Whistle",
        "Syngular Lead Melancholic Pluck",
        "Syngular Lead Panflute",
        "Syngular Seq Bass",
        "Syngular Seq Gate",
        "Syngular Seq Polaris",
        "Syngular Seq Rain Stick",
    ],
    # Synth Calliope (81) — Syngular Keys
    81: [
        "Syngular Keys Flash of Wisdom",
        "Syngular Keys Fractal Pulse",
        "Syngular Keys Harmonic Convergence",
        "Syngular Keys Lonely Pallas",
        "Syngular Keys Magnetic Flux",
        "Syngular Keys Nightcall",
        "Syngular Keys Phase Collapse",
        "Syngular Keys Replicant Dream",
        "Syngular Keys Sun Chariot",
        "Syngular Keys Sweep",
    ],
    # Pad (88) — Syngular Pad
    88: [
        "Syngular Pad Ancient Tree",
        "Syngular Pad Evolving Overtones",
        "Syngular Pad Inner Beat",
        "Syngular Pad Mixed Choir",
        "Syngular Pad Muted Background",
        "Syngular Pad Outer Rim",
        "Syngular Pad Phase Transition",
        "Syngular Pad Smooth",
        "Syngular Pad Strings Ensemble",
        "Syngular Pad Quantum Drift",
        "Syngular Pad Quantum Drift 2",
        "Syngular Pad Rusty Gears",
        "Syngular Pad Vibrational Field",
    ],
    # Kalimba (108)
    108: [
        "Kalimba Original",
        "Kalimba Binaural",
        "Kalimba Spacey",
    ],
    # Steel Drums (114) — Steel Drum, Spacedrum, Hand Pan, Tank Drum, Syngular Perc
    114: [
        "Syngular Perc Helmholtz Drops",
        "Syngular Perc Thin Square",
        "Steel Drum - natural",
        "Steel Drum - Binaural",
        "Steel Drum - sustain",
        "Steel Drum - dampers",
        "Steel Drum Spacious",
        "Steel Drum Dreamy",
        "Steel Drum Cinematic",
        "Steel Drum Bowed",
        "Spacedrum - natural, hand played",
        "Spacedrum Binaural",
        "Spacedrum - sustain, hand played",
        "Spacedrum - dampers, hand played",
        "Spacedrum - dreamy, hand played",
        "Spacedrum - natural, mallets",
        "Spacedrum - sustain, mallets",
        "Spacedrum - dampers, mallets",
        "Spacedrum - dreamy, mallets",
        "Hand Pan - natural, hand played",
        "Hand Pan Binaural",
        "Hand Pan - sustain, hand played",
        "Hand Pan - dampers, hand played",
        "Hand Pan - dreamy, hand played",
        "Hand Pan - natural, mallets",
        "Hand Pan - sustain, mallets",
        "Hand Pan - dampers, mallets",
        "Hand Pan - dreamy, mallets",
        "Tank Drum - natural",
        "Tank Drum Binaural",
        "Tank Drum - thin metal",
        "Tank Drum - dampers",
        "Tank Drum - thin metal, dampers",
        "Tank Drum - dreamy I",
        "Tank Drum - dreamy II",
    ],
}

# Flat list of all presets
ALL_PRESETS: List[str] = [p for presets in PROGRAM_TO_PRESETS.values() for p in presets]

AVAILABLE_PROGRAMS: List[int] = sorted(PROGRAM_TO_PRESETS.keys())


def get_preset(
    program: int = 0,
    rng: Optional[np.random.RandomState] = None,
) -> str:
    """Get a random preset for the given MIDI program number."""
    assert program in PROGRAM_TO_PRESETS, \
        f"No presets for program {program}. Available: {AVAILABLE_PROGRAMS}"
    presets = PROGRAM_TO_PRESETS[program]
    if rng is None:
        rng = np.random.RandomState()
    return presets[rng.randint(len(presets))]


def get_random_preset(
    rng: Optional[np.random.RandomState] = None,
    programs: Optional[List[int]] = None,
) -> tuple[str, int]:
    """Get a random preset from any (or specified) programs.

    Returns (preset_name, program_number).
    """
    if rng is None:
        rng = np.random.RandomState()
    if programs is None:
        programs = AVAILABLE_PROGRAMS
    prog = programs[rng.randint(len(programs))]
    return get_preset(prog, rng), prog
